version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jaishreeram 
      MYSQL_USER: axon-user
      MYSQL_PASSWORD: jaishreeram
      MYSQL_DATABASE: axon-db
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - axon-network 
  
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  axon-network: